### ISSUE TITLE
Remove sensitive data (API Keys)

### ISSUE THREAD

**Issue by luissilva1044894** [dherediat97/NextLevelServer#17]
Remove your Credentials / API Keys from url.js. You may use a .env or a local file for storing them instead! Also, remember to add the `.env` or local file in the `.gitignore`

**Comment by dherediat97** [comment]
Ok, Only is the same but stored in a file, I were thinking in a system with binary files because i can write since server side.

Many Thanks You @luis

**Comment by luissilva1044894** [comment]
@dherediat97 Are you using Heroku, right? You don't need a binary file for it.

The `.env` is something to be on your end, and it's why you may add it to `.gitignore`. It's not indeed to be public.

You may add you keys directly on Heroku Dashboard accessing: <https://dashboard.heroku.com/apps/nextlevelserver/settings>

Or you may set them using the Heroku CLI
```bash
heroku config:set HIREZ_API_KEY=1004
```

To use them on your code:
````js
var hirez_api_key = process.env.HIREZ_API_KEY;
````

Some articles that can be useful:
<https://devcenter.heroku.com/articles/config-vars>
<https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-config-vars>
<https://codeburst.io/process-env-what-it-is-and-why-when-how-to-use-it-effectively-505d0b2831e7>

**Comment by dherediat97** [comment]
ok thanks you, tomorrow i change that

**Comment by dherediat97** [comment]
![imagen](https://user-images.githubusercontent.com/17063135/67758908-d336a180-fa3e-11e9-8bb4-7d06ba0e5157.png)
Hey again @luissilva1044894, I did now, thanks for this issue, isnt for me important but its true that i have change that.

**Comment by luissilva1044894** [comment]
@dherediat97 Yo!

The main "issue" about API keys being public is that everyone have access and someone else could waste your api limits. I know that it's Paladins / Hi-Rez, no one care about. But you can avoid it by storing  your API keys in a .env instead having them on your source. I guess that some devs don't think/worry about that.

I'm not a Node.JS dev, but you can @ everytime you want or need.  🙂

**Comment by dherediat97** [comment]
> The main "issue" about API keys being public is that everyone have access and someone else could waste your api limits. I know that it's Paladins / Hi-Rez, no one care about. But you can avoid it by storing your API keys in a .env instead having them on your source. I guess that some devs don't think/worry about that.

Yes, i know it, but there are many things that i have resolve in this proyect and that was the main, so nothing more. Other things is reuse the sessionID... Many things i know that have fails in my code but  all with my time is resolved.

😄 

Greetings

**Comment by luissilva1044894** [comment]
This isn't the same issue, but... What do you mean `reuse the sessionId`? This? <https://github.com/dherediat97/NextLevelServer/blob/a19bb8f06d5210baa43f5d50d1373c266781a24e/server/main.js#L41>

Instead of calling `initSessionHIREZ` in every single method, move the logic to <https://github.com/dherediat97/NextLevelServer/blob/a19bb8f06d5210baa43f5d50d1373c266781a24e/server/main.js#L174>


Your new logic is:
If session_id is null or "" then, request a new and save the received session_id (`initSessionHIREZ()` call)
Try to use the previously stored session_id
If response_json.ret_msg is not null and contains `Invalid session id` then, request a new session_id and try to request again (Recursion)
```js
initSessionHIREZ()
return getDataHIREZ(signature, res, format_type, id_champ)
```
return response_json


Also, you can store the `session_id` locally or in a db (Keep in mind that [Heroku deletes all files every restart](https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted) - Which means: Deploy, restart, shut down, cycling)
